Rental/Models/CarInventory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;



namespace Rental.Models
{
    public class CarInventory
    {
        public int CarTypeId { get; set; }
        [Key]
        public int ID { get; set; }
        public string Color { get; set; }
        public string Engine { get; set; }
        public string CarTypeName { get; set; }
        public Nullable<decimal> PricePerDay { get; set; }
        public List<OrderList> OrderLists { get; set; }


        //public virtual List<OrderList> OrderLists { get; set; }

    }
}

Rental/Models/CarModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Rental.Models
{
    public class CarModel // מותאם ל שדות בדטה בייס
    {

        public int carTypeID { get; set; }
        public string modelName { get; set; }
        public string manufactorName { get; set; }
        public string manufactorYear { get; set; }
        public string categorie { get; set; }
        public decimal pricePerDay { get; set; }

       
    }
}

Rental/Models/OrderList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rental.Models
{
    public class OrderList
    {
        //public partial class OrderList
        //{
        [Key]
        public int OrderID { get; set; }
        public string CustName { get; set; }
        //[ForeignKey("ID")]
        public int CarID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime PickUpDate { get; set; }
        public System.DateTime DropOffDate { get; set; }
        public Nullable<decimal> DiscountCode { get; set; }
        public Nullable<decimal> OrderCost { get; set; }
        [ForeignKey("CarID")]
        public CarInventory CarInventory { get; set; }

        //public virtual carinventory CarinventoryOld { get; set; }
        //}
    }
}

Rental/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rental.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult About()
        {
            ViewBag.Title = "About";
            return View();
        }
    }
}

Rental/Controllers/CarListApiController.cs
using Rental.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;
using Rental.Dal;
using Rental.BE_Logic;


namespace Rental.Controllers
{
    public class CarListApiController : ApiController
    {
     
        public IEnumerable<CarInventory> GetAllCars() // the methoda is called because its named Get... and by the call from the JQuery
        {
            //using (RentCarEntities dal=new RentCarEntities())
            //{
            //    return dal.carinventories.ToList();
            //}
            using (CarsDal dal = new CarsDal())
            {
                return dal.CarInventories.ToList();
                //return null;
            }
        }


        //method : returns car details by car ID (number)
        public CarInventory GetChosenCar(int CarID) // the methoda is called because its named Get... and by the call from the JQuery
        {

            //using (RentCarEntities dal=new RentCarEntities())
            //{
            //    return dal.carinventories.ToList();
            //}
            using (CarsLogic carsfromdb = new CarsLogic())
            {
                return carsfromdb.ChosenCar(CarID);
            }

        }

        //method returns chosen car by selected type from select tag
        public IQueryable<CarInventory> GetCarByCategory(string CarTypeName)
        {

            using (CarsLogic carsByCategory = new CarsLogic())
            {
                return carsByCategory.CarByCategory(CarTypeName).AsQueryable();
                //return from x in dal.CarInventories
                //       where x.CarTypeName.Contains(CarTypeName)
                //       select x;
            }
        }


        // not working yet
        public IQueryable<CarInventory> PostAvailableCars(DateTime dateIn, DateTime dateOut)
        {

            using (CarsLogic availableCars = new CarsLogic())
            {

                //DateTime parsedIn = DateTime.Parse(dateIn);
                //DateTime parsedOut = DateTime.Parse(dateOut);
                DateTime parsedIn = dateIn;
                DateTime parsedOut = dateOut;
                return availableCars.AvailableCars(parsedIn, parsedOut).AsQueryable();
                //return from x in dal.CarInventories
                //       where x.CarTypeName.Contains(CarTypeName)
                //       select x;
            }
        }

        //not working yet brcause of date type 

        public IQueryable<CarInventory> postneworder(string carType, DateTime dateIn, DateTime dateOut)
        {

            using (CarsLogic availableCars = new CarsLogic())
            {
                string cType = carType;
                DateTime In = dateIn;
                DateTime Out = dateOut;
                return availableCars.AvailableCars(dateIn, dateOut).AsQueryable();
                //return from x in dal.CarInventories
                //       where x.CarTypeName.Contains(CarTypeName)
                //       select x;
            }
        }

        //public IHttpActionResult GetCar(int id) //GET that returns value by parameter.
        //{

        //    var car = dal.carinventories.FirstOrDefault(c => c.CarID == id); //compare cartypeID to id;
        //    if (car == null)
        //    {
        //        return NotFound();
        //    }
        //    return Ok(car);
        //}

    }
}

Rental/Controllers/CarOrdersApiController.cs
using Rental.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;
using Rental.Dal;

//using Rental_BE;

namespace Rental.Controllers
{
    public class CarOrdersApiController : ApiController
    {
        //private RentCarEntities dal = new RentCarEntities();
        //private CarsDal dal = new CarsDal();

        public List<OrderList> GetAllOrders() // the methoda is called because its named Get... and by the call from the JQuery
        {
            using (CarsDal dal = new CarsDal())
            {
                return dal.OrderLists.ToList();

            }
        }
    }
}

Rental/Controllers/CarsDescriptionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rental.Controllers
{
    public class CarsDescriptionController : Controller
    {
        // GET: CarsDescription
        public ActionResult CarsDescription_View()
        {
            ViewBag.Title = "רכבים מומלצים";
            return View();
        }
    }
}

Rental/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rental.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Home()
        {
            return View();
        }
    }
}

Rental/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rental.Controllers
{
    public class OrdersController : Controller
    {
        // GET: Orders_View
        public ActionResult Orders_View()
        {
            ViewBag.Title = "הזמנות";
            return View();
        }
    }
}

Rental/Controllers/RentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rental.Controllers
{
    public class RentController : Controller
    {
        // GET: Rent
        public ActionResult NewRent_ToView()
        {
            ViewBag.Title = "New Rental";
            return View();
        }
    }
}

Rental/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rental.Controllers
{
    public class SalesController : Controller
    {
        // GET: Sales
        public ActionResult Sales_View()
        {
            ViewBag.Title = "מבצעים חמים";
            return View();
        }
    }
}

Rental/Views/About/About.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>About</title>
</head>

<body>
    <h3>@ViewBag.Title</h3>
    <div>
        <img src="~/Pictures/d49647b1-cd8c-e5b1.png" />
        <img src="~/Pictures/d49647b1-7f39-0b6b.png" />
        <img src="~/Pictures/d49647b1-e7d8-7c33.png" />
        <img src="~/Pictures/d49647b1-e7f9-a631.png" />
    </div>
</body>
</html>

Rental/Views/CarsDescription/CarsDescription_View.cshtml
@{
   
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>
<main dir="rtl">
    <section>
        <a href="#יונדאי אקסנט">יונדאי אקסנט</a>
        <p>
            יונדאי i20 החדשה, יותר ממה שחלמתם
            עיצוב צעיר ודינאמי, מערכות בטיחות מתקדמות הכוללות גם בלימה אוטונומית של הרכב במצבי חירום.
            חלל פנים מאוורר ומפנק הכולל גלגל הגה וידית הילוכים מעור, שמשות כהות*, תא כפפות מקורר ומערכת Connected Car המאפשרת לכם להישאר מחוברים בכל מקום ובכל זמן.
        </p>

    </section> <!---->
    <section>
        <a href="#יונדאי I 20">יונדאי i20</a>
        <p>
            ליסינג  טרייד אין  קנייה | מימון
            חוות דעת	- קיה פיקנטו
            קיה פיקנטו היא מכונית מיני עירונית ומאוד פופולארית. הדור הנוכחי שלה, זה שהגיע לישראל בשנת 2017, עבר מקצה שיפורים מקיף ביחס לקודמו - אך עדיין שמר על אותם מאפיינים בסיסיים. קיה פיקנטו נראית טוב מאוד, וגם מבפנים מרגישה איכותית ובוגרת - אם כי היא לא צבעונית ושמחה כמו חלק מהמתחרות. המרווח הפנימי בסדר גמור, וגם תא המטען גדל במעט

        </p>

    </section>
    <section>
        <a href="#mazda">מזדה</a>
        <p>
            אקסנט היא מכונית סופר מיני בתצורת סדאן או האצ'בק עם ארבע או חמש דלתות, המיועדת בעיקר לשווקים מתפתחים. בדורות המאוחרים היא חולקת את הפלטפורמה עם קיה ריו. הדור הרביעי הוצג בשנת 2010. הוא שווק בישראל תחת השם i25 אקסנט, וכך גם בקולומביה. הוא מגיע עם מנוע בנזין בנפח 1.4 ליטר ו-1.6 ליטר המפיקים 109 ו-126 כ״ס בהתאמה, ותיבת הילוכים ידנית בעלת 5 או 6 הילוכים ותיבה אוטומטית בעלת 4 או 6 הילוכים.

        </p>

    </section>

</main>

Rental/Views/CarsList/Inde2x.cshtml
@using Rental.Models
@model List<CarInventory>
    


@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@foreach (CarInventory car in Model)
{
    @car.carTypeID
    <span></span>
    @car.carId
    @car.color
    @car.engine
    <br />
}

Rental/Views/CarsList/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <div>
        <h1>Search Car</h1>
        <input type="text" id="carId" />
        <input type="button" value="Search With ID" onclick="Search()" />
        <p id="car" />
    </div>
    <div>
        <h2>List Of Cars:</h2>
        <ul id="cars"></ul>
    </div>
    <script src="Scripts/jquery-3.3.1.min.js"></script>
    <script>var uri = '/api/carlistapi/';
        $(document).ready(function () {
            $.getJSON(uri).done(function (data) {
                $.each(data, function (key, value) {

                    $('<li>', { text: getData(value) }).appendTo($('#cars'));

                });
            });

        });
        function getData(data) { return data.CarID + '' + data.CarTypeID + data.Color; }
        function Search() {
            var id = $('#carId').val();

            $.getJSON(uri + id, function (d) {
                if (d != null) {
                    $('#car').html(getData(data));
                }
                if (d == null) {
                    $('#car').html('The Error Is:' + error);
                }
                //).done(function (data) {
                //    $('#car').text(getData(data));
                //}).fail(function (jqXHR, MyError, error) {
                //    $('#car').text('The Error Is:' + error);
                //});

            });

        }</script>

</body>
</html>
@*@@Html.DisplayName(d=>d.)@*@

@*@foreach (CarInventory car in Model)
    {
        @car.CarTypeID
        <span></span>
        @car.CarID<br/>
        @car.Color
    }*@

Rental/Views/Orders/Orders_View.cshtml
@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>@ViewBag.Title</h2>
<form id="newRental">

    שם הלקוח: <input id="customer" name="customer" required value="" class="form-control" />
    <select id="chooseCarType" required value="" class="form-control">
        <option value="">בחר סוג רכב</option>
        <option value="mini">mini</option>
        <option value="Compact">Compact</option>
        <option value="Standard">Standard</option>
        <option value="Family">Family</option>
        <option value="Full Size">Full Size</option>
    </select>
    תאריך איסוף: <input type="date" name="dateIn" id="dateIn" required value="" class="form-control" />
    תאריך איסוף <input type="date" name="dateOut" id="dateOut" required value="" class="form-control">
    <div>
        <ul></ul>
    </div>
    <button id="showOrders" class="form-control-static">show me all orders</button>
    <br />
    <br />

    @*button that shows available cars*@
    <button id="carType">Show chosen CarType</button>
    <div>
        <h2>List Of Cars:</h2>
        <ul id="cars"></ul>
    </div>
    <table id="Tab" width="200px" border="1" class="table table-bordered">
        <thead>
            <tr>
                <th>מס הזמנה</th>
                <th>שם לקוח</th>
                <th>מס רכב</th>
                <th>תאריך הזמנה</th>
                <th>תאריך איסוף</th>
                <th>תאריך החזרה</th>
                <th>תאריך איסוף</th>
                <th><button>choose</button></th>
            </tr>
        </thead>
    </table>

    @*Update Orders Using a Post Method*@
    <input type="text" id="id" value="insertCarID" class="form-control" />
    <button id="CarOrder">קבל הצעה</button>
    <p id="carWithId" />
    <br />

    <input type="text" id="custName" placeholder="Customer Name" />
    <input type="text" id="carId" placeholder="car Number" />
    <input type="text" id="pickUpDate" placeholder="Pick up Date" />
    <input type="text" id="dropOffDate" placeholder="Return Day" />
   
    
    <button id="postButton">Post</button>

</form>
<script src="~/Scripts/jquery-3.3.1.js"></script>
<script>
    //show all orders
    $('#showOrders').click(function () {
        $.getJSON('/api/carordersapi/', function (data) {
            alert("Hello");
            $.each(data, function (key, value) {
                $('<tbody><tr><td>' + value.OrderID + '</td><td>' + value.CustName + '</td><td>' + value.CarID + '</td><td>' + value.OrderDate + '</td><td>' + value.PickUpDate + '</td><td>' + value.DropOffDate + '</td><td>'+'<button>' + 'choose' + '</button>' + '</td></tr></tbody>').appendTo($('#Tab'));
            });
        });
    });

    $('#postButton').click(function () {
        var custName = $('#custName').val();
        var carID = $('#carId').val();
        var orderday = $.now();
        var pickupday = $('#pickUpDate').val();
        var dropfodate = $('#dropOffDate').val();
        $.ajax({
            type: 'Post',
            contentType: 'application/json;charset=utf-8',
            url: '/api/carordersapi',
            data: JSON.stringify({
                custName: CustName,
                orderday: OrderDaterID,
                pickupday: PickUpDate,
                dropfodate: DropOffDate,
                CarTypeId: carTypeID,
                CarID: ID
            }),
            dataType: 'json',
            success: function () {
                $.getJSON('/api/carordersapi/', function (data) {
                    $.each(data, function (key, value) {
                        $('<tr><td>' + value.CarTypeName + '</td><td>' + value.Color + '</td><td>' + value.Engine + '</td><td>' + '<button>' + 'choose' + '</button>' + '</td></tr>').appendTo($('#Tab'));
                    });
                });
            }
        });
    });

</script>
<style>
    table th {
        width: auto !important;
    }
</style>

Rental/Views/Rent/NewRent_ToView.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h1>@ViewBag.Title</h1>
<form id="newRental">

    <select id="chooseCarType" required value="" class="form-control">
        <option value="">בחר סוג רכב</option>
        <option value="mini">mini</option>
        <option value="Compact">Compact</option>
        <option value="Standard">Standard</option>
        <option value="Family">Family</option>
        <option value="Full Size">Full Size</option>
    </select>
    תאריך איסוף: <input type="date" name="dateIn" id="dateIn" class="form-control" />
    תאריך החזרה: <input type="date" name="dateOut" id="dateOut" required value="" class="form-control">
    <div>
        <ul></ul>
    </div>
    <button id="carType" class="form-control-static">Show chosen CarType</button>
    <button id="availableCars" class="form-control-static">מצא רכבים פנויים</button>
    <br />
    <br />

    <button id="showAllCars">Show all cars</button>

    <div>
        <h2>List Of Cars:</h2>
        <ul id="cars"></ul>

    </div>
    <table id="Tab" width="200px" border="1">
        <tr>
            <th>car type</th>
            <th>color</th>
            <th>engine</th>
            <th>carid</th>
            <th>price</th>
            <th><button>choose</button></th>
        </tr>
    </table>


    <input type="text" id="id" value="insertCarID" class="form-control" />
    <button id="CarOrder">קבל הצעה</button>
    <p id="carWithId" />
    <br />

    @*Update Button Using a Post Method*@
    <input type="text" id="carTypeName" placeholder="name of car" />
    <input type="text" id="color" placeholder="color of car" />
    <input type="text" id="engine" placeholder="engine of car" />
    <input type="text" id="carTypeID" placeholder="carTypeID of car" />
    <input type="text" id="carID" placeholder="carID of car" />
    <input type="text" id="carPrice" placeholder="carPrice of car" />

    <button id="postButton">Post</button>

</form>


<main dir="rtl">
    <section>
        <a href="#יונדאי אקסנט">יונדאי אקסנט</a>
        <p>
            יונדאי i20 החדשה, יותר ממה שחלמתם
            עיצוב צעיר ודינאמי, מערכות בטיחות מתקדמות הכוללות גם בלימה אוטונומית של הרכב במצבי חירום.
            חלל פנים מאוורר ומפנק הכולל גלגל הגה וידית הילוכים מעור, שמשות כהות*, תא כפפות מקורר ומערכת Connected Car המאפשרת לכם להישאר מחוברים בכל מקום ובכל זמן.
        </p>

    </section> <!---->
    <section>
        <a href="#יונדאי I 20">יונדאי i20</a>
        <p>
            ליסינג  טרייד אין  קנייה | מימון
            חוות דעת	- קיה פיקנטו
            קיה פיקנטו היא מכונית מיני עירונית ומאוד פופולארית. הדור הנוכחי שלה, זה שהגיע לישראל בשנת 2017, עבר מקצה שיפורים מקיף ביחס לקודמו - אך עדיין שמר על אותם מאפיינים בסיסיים. קיה פיקנטו נראית טוב מאוד, וגם מבפנים מרגישה איכותית ובוגרת - אם כי היא לא צבעונית ושמחה כמו חלק מהמתחרות. המרווח הפנימי בסדר גמור, וגם תא המטען גדל במעט

        </p>

    </section>
    <section>
        <a href="#mazda">מזדה</a>
        <p>
            אקסנט היא מכונית סופר מיני בתצורת סדאן או האצ'בק עם ארבע או חמש דלתות, המיועדת בעיקר לשווקים מתפתחים. בדורות המאוחרים היא חולקת את הפלטפורמה עם קיה ריו. הדור הרביעי הוצג בשנת 2010. הוא שווק בישראל תחת השם i25 אקסנט, וכך גם בקולומביה. הוא מגיע עם מנוע בנזין בנפח 1.4 ליטר ו-1.6 ליטר המפיקים 109 ו-126 כ״ס בהתאמה, ותיבת הילוכים ידנית בעלת 5 או 6 הילוכים ותיבה אוטומטית בעלת 4 או 6 הילוכים.
        </p>
    </section>
</main>

<script src="~/Scripts/jquery-3.3.1.js"></script>
<script>

    //var tblCars = "<tr><th>CAR TYPE</th><th>COLOR</th><th>ENGINE</th><th>CarID</th><th><button>Choose</button></th></tr>";
    $('#showAllCars').click(function () {
        $("#Tab").find("tr:gt(0)").remove();
        $.getJSON('/api/carlistapi/', function (data) {
            $.each(data, function (key, value) {
                $('<tr><td>' + value.CarTypeName + '</td><td>' + value.Color + '</td><td>' + value.Engine + '</td><td>' +  value.ID+ '</td><td>' + '<button id="alt">' + 'choose' + '</button>' + '</td></tr>').appendTo($('#Tab'));
            });
        });
    });

    //method to show chosen datatable by slected car type
    $("#carType").click(function () {
        $("#Tab").find("tr:gt(0)").remove();
        var carType = $("#chooseCarType option:selected").val();
        //alert($("#chooseCarType option:selected").val());
        $.getJSON('/api/carlistapi?CarTypeName=' + carType, function (data) {
            $.each(data, function (key, value) {
                $('<tr><td>' + value.CarTypeName + '</td><td>' + value.Color + '</td><td>' + value.Engine + '</td><td>' + value.ID + '</td><td>' + value.PricePerDay + '</td><td>' + '<button>' + 'choose' + '</button>' + '</td></tr>').appendTo($('#Tab'));
            });
        });
    });

    //method for choosing between two dates

    //$("#availableCars").click(function () {
    //    var dateIN = $("#dateIn").val();
    //    alert($("#dateIn").val());
    //    $.getJSON('/api/carlistapi?PickUpDate=' + dateIN, function (data) {
    //        $.each(data, function (key, value) {
    //            $('<tbody><tr><td>' + value.OrderID + '</td><td>' + value.CustName + '</td><td>' + value.CarID + '</td><td>' + value.OrderDate + '</td><td>' + '</td><td>' + value.PickUpDate + '</td><td>' + '</td><td>' + value.DropOffDate + '</td><td>' + '<button>' + 'choose' + '</button>' + '</td></tr></tbody>').appendTo($('#Tab'));
    //        });
    //    });
    //});


    //Method: show availble cars to rent by date
    $('#availableCars').click(function () {
        var carType = $('#chooseCarType option:selected').val();
        var dateI = $('#dateIn').val();
        var dateO = $('#dateOut').val();
        $.ajax({
            type: 'Post',
            contentType: 'application/json;charset=utf-8',
            url: 'api/carlistapi',
            data: JSON.stringify({
                //CarTypeName: carType,
                PickUpDate: dateI,
                DropOffDate: dateO
            }),
            dataType: 'json',
            success: function () {
                $.getJSON('/api/carlistapi', function (data) {
                    $.each(data, function (key, value) {
                        $('<tr><td>' + value.CarTypeName + '</td><td>' + value.Color + '</td><td>' + value.Engine + '</td><td>' + '<button>' + 'choose' + '</button>' + '</td></tr>').appendTo($('#Tab'));
                    });
                });
            }
        });
    });



    //method : add new car
    $('#postButton').click(function () {
        alert('hello');
        var ctm = $('#carTypeName').val();
        var color = $('#color').val();
        var engine = $('#engine').val();
        var carTypeID = $('#carTypeID').val();
        var carID = $('#carID').val();
        alert(ctm);
        // post request by ajax doesnt work 
        $.ajax({
            type: 'Post',
            contentType: 'application/json;charset=utf-8',
            url: '/api/carlistapi',
            data: JSON.stringify({
                CarTypeName: ctm,
                Color: color,
                Engine: engine,
                CarTypeId: carTypeID,
                CarID: ID
            }),
            dataType: 'json',
            success: function () {
                $.getJSON('/api/carlistapi/', function (data) {
                    $.each(data, function (key, value) {
                        $('<tr><td>' + value.CarTypeName + '</td><td>' + value.Color + '</td><td>' + value.Engine + '</td><td>' + '<button>' + 'choose' + '</button>' + '</td></tr>').appendTo($('#Tab'));
                    });
                });
            }
        });
    });

    $('#alt').click(function () {
        alert('Order Made');
    });

</script>
<script>
    $(function () {
        $('#CarOrder').click(function () {
            var idCar = $('#id').val();
            $.getJSON('/api/carlistapi?CarID=' + idCar, function (data) {
                alert(data.carID);
                //$('<tr><td>' + value.CarTypeName + '</td><td>' + value.Color + '</td><td>' + value.Engine + '</td><td>' + '<button>' + 'choose' + '</button>' + '</td></tr>').appendTo($('#Tab'));
                $('#carWithId').text(data.CarTypeName + data.Color + data.Engine + data.ID + data.CarTypeId).appendTo($('#carWithId'))

            });
        });
    });
</script>
<style>
    #holdy {
        width: 350px;
        height: 380px;
        padding: 3px;
        margin: 0 auto;
        border: 1px solid red;
        position: relative;
    }

    #blackBlock {
        background: #000;
        opacity: 0.6;
        width: 340px;
        height: 102px;
        position: absolute;
        top: 185px;
        line-height: 100px;
        text-align: center;
    }

        #blackBlock a {
            color: white;
            text-decoration: none;
            font-size: 2.2em;
        }

            #blackBlock a:hover {
                text-decoration: underline;
            }

    #listSlide {
        margin-top: 75px;
        padding: 0;
        margin-left: 10px;
        list-style: none;
    }

        #listSlide li {
            float: left;
            margin: 3px;
            padding: 0;
        }

            #listSlide li img {
                cursor: pointer;
            }
</style>

Rental/Views/Shared/_Layout.cshtml
@using System.Web.Optimization

<!DOCTYPE html>

<html>
<head>
    @*<link rel="stylesheet" type="text/css" href="~/Content/bootstrap.css" />*@
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"/>
    <link rel="stylesheet" type="text/css" href="~/Content/Site.css" />
    @Styles.Render("~/Content/css")  @*זה בעצם הכתובת של הבוטסטראפ עם הבנדלים*@

    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <title>_Layout</title>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("דף הבית", "NewRent_ToView", "Rent", new { area = "דף הבית" }, new { @class = "navbar-brand" })
            </div>

            <div class="navbar-collapse collapse">
                <ul class="navbar-nav">
                    <li>
                        @Html.ActionLink("מבצעים", "Sales_View", "Sales", new { area = "Sales" }, new { @class = "navbar-brand" })
                    </li>
                    <li>
                        @Html.ActionLink("הזמנות", "Orders_View", "Orders", new { area = "Orders" }, new { @class = "navbar-brand" })
                    </li>
                    <li>
                        @Html.ActionLink("רכבים מומלצים", "CarsDescription_View", "CarsDescription", new { area = "CarsDescription" }, new { @class = "navbar-brand" })

                    </li>
                    <li>

                        @Html.ActionLink("קצת עלינו", "About", "About", new { area = "קצת עלינו" }, new { @class = "navbar-brand" })
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
</body>
</html>